import type { Forecast, InventoryRow, Recommendation, Sentiment, Shipment, Supplier, Warehouse } from "./types";

const stamp = "2026-09-08T08:30:00.000Z";
export const warehouses: Warehouse[] = [
  { id: "wh-dhaka", name: "Dhaka Central", region: "Dhaka", latitude: 23.8103, longitude: 90.4125, capacity: 98000, utilization: .78, inventory_value: 1824000, risk_score: .68, risk_level: "HIGH", status: "watch" },
  { id: "wh-ctg", name: "Chattogram Port", region: "Chattogram", latitude: 22.3569, longitude: 91.7832, capacity: 72000, utilization: .61, inventory_value: 1298000, risk_score: .44, risk_level: "MEDIUM", status: "stable" },
  { id: "wh-raj", name: "Rajshahi North", region: "Rajshahi", latitude: 24.3745, longitude: 88.6042, capacity: 54000, utilization: .49, inventory_value: 864500, risk_score: .29, risk_level: "LOW", status: "stable" },
  { id: "wh-syl", name: "Sylhet East", region: "Sylhet", latitude: 24.8949, longitude: 91.8687, capacity: 42000, utilization: .83, inventory_value: 642700, risk_score: .76, risk_level: "CRITICAL", status: "critical" },
];
export const inventory: InventoryRow[] = [
  { id: "inv-1", warehouse_id: "wh-dhaka", warehouse_name: "Dhaka Central", product_id: "sku-oil-1", sku: "OIL-1L-SUN", product_name: "Sunflower Oil 1L", category: "Cooking Oil", quantity: 4200, reserved: 540, incoming: 1800, available_inventory: 5460, average_daily_demand: 720, days_of_inventory: 6.2, safety_stock: 2880, reorder_point: 8640, stockout_probability: .73, excess_inventory: 0, inventory_risk: "HIGH", unit_value: 38, updated_at: stamp },
  { id: "inv-2", warehouse_id: "wh-dhaka", warehouse_name: "Dhaka Central", product_id: "sku-rice-5", sku: "RICE-5KG-BAS", product_name: "Basmati Rice 5kg", category: "Staples", quantity: 18800, reserved: 1200, incoming: 6200, available_inventory: 23800, average_daily_demand: 610, days_of_inventory: 29.7, safety_stock: 2440, reorder_point: 6100, stockout_probability: .18, excess_inventory: 0, inventory_risk: "LOW", unit_value: 22, updated_at: stamp },
  { id: "inv-3", warehouse_id: "wh-dhaka", warehouse_name: "Dhaka Central", product_id: "sku-milk-1", sku: "MILK-1L-UHT", product_name: "UHT Milk 1L", category: "Dairy", quantity: 2600, reserved: 380, incoming: 900, available_inventory: 3120, average_daily_demand: 450, days_of_inventory: 4.8, safety_stock: 1800, reorder_point: 4500, stockout_probability: .82, excess_inventory: 0, inventory_risk: "CRITICAL", unit_value: 22, updated_at: stamp },
  { id: "inv-4", warehouse_id: "wh-ctg", warehouse_name: "Chattogram Port", product_id: "sku-oil-1", sku: "OIL-1L-SUN", product_name: "Sunflower Oil 1L", category: "Cooking Oil", quantity: 6400, reserved: 460, incoming: 3200, available_inventory: 9140, average_daily_demand: 680, days_of_inventory: 13.4, safety_stock: 2720, reorder_point: 8160, stockout_probability: .38, excess_inventory: 0, inventory_risk: "MEDIUM", unit_value: 38, updated_at: stamp },
  { id: "inv-5", warehouse_id: "wh-ctg", warehouse_name: "Chattogram Port", product_id: "sku-rice-5", sku: "RICE-5KG-BAS", product_name: "Basmati Rice 5kg", category: "Staples", quantity: 14400, reserved: 900, incoming: 3500, available_inventory: 17000, average_daily_demand: 540, days_of_inventory: 25, safety_stock: 2160, reorder_point: 5400, stockout_probability: .14, excess_inventory: 0, inventory_risk: "LOW", unit_value: 22, updated_at: stamp },
  { id: "inv-6", warehouse_id: "wh-raj", warehouse_name: "Rajshahi North", product_id: "sku-lentil-1", sku: "DAL-1KG-RED", product_name: "Red Lentils 1kg", category: "Staples", quantity: 9600, reserved: 430, incoming: 1300, available_inventory: 10470, average_daily_demand: 310, days_of_inventory: 33.2, safety_stock: 1240, reorder_point: 3720, stockout_probability: .09, excess_inventory: 0, inventory_risk: "LOW", unit_value: 22, updated_at: stamp },
  { id: "inv-7", warehouse_id: "wh-syl", warehouse_name: "Sylhet East", product_id: "sku-oil-1", sku: "OIL-1L-SUN", product_name: "Sunflower Oil 1L", category: "Cooking Oil", quantity: 1600, reserved: 250, incoming: 400, available_inventory: 1750, average_daily_demand: 420, days_of_inventory: 3.8, safety_stock: 1680, reorder_point: 5040, stockout_probability: .91, excess_inventory: 0, inventory_risk: "CRITICAL", unit_value: 38, updated_at: stamp },
  { id: "inv-8", warehouse_id: "wh-syl", warehouse_name: "Sylhet East", product_id: "sku-milk-1", sku: "MILK-1L-UHT", product_name: "UHT Milk 1L", category: "Dairy", quantity: 980, reserved: 180, incoming: 250, available_inventory: 1050, average_daily_demand: 210, days_of_inventory: 3.3, safety_stock: 840, reorder_point: 2100, stockout_probability: .94, excess_inventory: 0, inventory_risk: "CRITICAL", unit_value: 22, updated_at: stamp },
];
export const forecasts: Forecast[] = [
  { warehouse_id: "wh-dhaka", product_id: "sku-oil-1", product_name: "Sunflower Oil 1L", horizon: "7d", predicted_demand: 9850, lower_bound: 9210, upper_bound: 10540, confidence: .91, model_name: "seasonal_baseline", model_version: "phase1.0", generated_at: stamp },
  { warehouse_id: "wh-dhaka", product_id: "sku-oil-1", product_name: "Sunflower Oil 1L", horizon: "30d", predicted_demand: 41400, lower_bound: 36500, upper_bound: 46800, confidence: .84, model_name: "seasonal_baseline", model_version: "phase1.0", generated_at: stamp },
  { warehouse_id: "wh-syl", product_id: "sku-oil-1", product_name: "Sunflower Oil 1L", horizon: "7d", predicted_demand: 2940, lower_bound: 2530, upper_bound: 3440, confidence: .87, model_name: "seasonal_baseline", model_version: "phase1.0", generated_at: stamp },
  { warehouse_id: "wh-dhaka", product_id: "sku-milk-1", product_name: "UHT Milk 1L", horizon: "7d", predicted_demand: 3680, lower_bound: 3340, upper_bound: 4050, confidence: .88, model_name: "seasonal_baseline", model_version: "phase1.0", generated_at: stamp },
];
export const sentiment: Sentiment[] = [
  { region: "Dhaka", product_category: "Cooking Oil", sentiment_score: .72, sentiment_change: .18, demand_signal: .84, confidence: .91, sample_count: 1840, trend: "rising" },
  { region: "Chattogram", product_category: "Cooking Oil", sentiment_score: .61, sentiment_change: .06, demand_signal: .68, confidence: .88, sample_count: 920, trend: "rising" },
  { region: "Sylhet", product_category: "Dairy", sentiment_score: .48, sentiment_change: -.12, demand_signal: .54, confidence: .82, sample_count: 610, trend: "falling" },
  { region: "Rajshahi", product_category: "Staples", sentiment_score: .66, sentiment_change: .02, demand_signal: .62, confidence: .86, sample_count: 740, trend: "stable" },
];
export const suppliers: Supplier[] = [
  { id: "sup-aci", name: "ACI Consumer Brands", region: "Dhaka", on_time_rate: .93, lead_time_days: 8, lead_time_variance_days: 1.4, active_products: 28, capacity_status: "available" },
  { id: "sup-meghna", name: "Meghna Group Foods", region: "Chattogram", on_time_rate: .88, lead_time_days: 10, lead_time_variance_days: 2.3, active_products: 19, capacity_status: "constrained" },
  { id: "sup-pran", name: "PRAN-RFL Group", region: "Rajshahi", on_time_rate: .91, lead_time_days: 7, lead_time_variance_days: 1.8, active_products: 23, capacity_status: "available" },
];
export const shipments: Shipment[] = [
  { id: "shp-4491", supplier_name: "Meghna Group Foods", destination: "Chattogram Port", vessel_id: "MV Bengal Star", eta: "12 Sep 2026", status: "At sea · 67% complete", delay_days: 2, risk_score: .64, latitude: 20.12, longitude: 89.32 },
  { id: "shp-4484", supplier_name: "ACI Consumer Brands", destination: "Dhaka Central", vessel_id: "Road convoy BD-22", eta: "09 Sep 2026", status: "In transit", delay_days: 0, risk_score: .18, latitude: 23.45, longitude: 90.11 },
];
export const recommendations: Recommendation[] = [
  { id: "rec-1001", decision_type: "RESTOCK", warehouse_id: "wh-dhaka", warehouse_name: "Dhaka Central", product_id: "sku-oil-1", product_name: "Sunflower Oil 1L", sku: "OIL-1L-SUN", recommended_quantity: 2400, supplier_id: "sup-aci", supplier_name: "ACI Consumer Brands", urgency: "HIGH", risk_score: .73, confidence: .91, forecast_demand: 9850, current_inventory: 4200, days_of_inventory: 6.2, expected_stockout_probability: .084, drivers: ["regional_demand_increase", "positive_consumer_sentiment", "supplier_lead_time_increase"], requires_human_approval: true, approval_status: "pending", expected_cost: 91200, created_at: stamp, explanation: { what: "Order 2,400 cases of Sunflower Oil 1L for Dhaka Central.", how_much: "The target covers the next forecast window plus safety stock while respecting the supplier case pack.", when: "Place the order now: 6.2 days of inventory is below the 8-day lead-time envelope.", from_where: "ACI Consumer Brands has 93% on-time performance and the best available lead-time/capacity mix.", why: "Forecast demand is rising alongside aggregated positive Dhaka sentiment, while supplier lead time is widening.", risk: "Demand may normalize faster than expected or the shipment may arrive late; approval and the next inventory event remain required.", confidence: "91%; the phase-one baseline is deterministic until the trained forecasting adapter is enabled." } },
  { id: "rec-1002", decision_type: "RESTOCK", warehouse_id: "wh-syl", warehouse_name: "Sylhet East", product_id: "sku-milk-1", product_name: "UHT Milk 1L", sku: "MILK-1L-UHT", recommended_quantity: 1800, supplier_id: "sup-pran", supplier_name: "PRAN-RFL Group", urgency: "CRITICAL", risk_score: .88, confidence: .86, forecast_demand: 3680, current_inventory: 980, days_of_inventory: 3.3, expected_stockout_probability: .94, drivers: ["low_days_of_inventory", "perishable_shelf_life", "regional_supply_risk"], requires_human_approval: true, approval_status: "pending", expected_cost: 39600, created_at: stamp, explanation: { what: "Order 1,800 cases of UHT Milk 1L for Sylhet East.", how_much: "The policy target covers demand plus perishable safety stock and is rounded to case pack.", when: "Escalate today: coverage is 3.3 days against a 7-day supplier lead time.", from_where: "PRAN-RFL Group is available with a 7-day lead time and 91% on-time performance.", why: "Low coverage and shelf-life constraints make this a critical replenishment decision.", risk: "A late shipment can cause a stockout; a rapid demand reversal can create short-dated excess.", confidence: "86%; confidence is reduced for the smaller regional signal sample." } },
  { id: "rec-0998", decision_type: "RESTOCK", warehouse_id: "wh-ctg", warehouse_name: "Chattogram Port", product_id: "sku-oil-1", product_name: "Sunflower Oil 1L", sku: "OIL-1L-SUN", recommended_quantity: 1600, supplier_id: "sup-meghna", supplier_name: "Meghna Group Foods", urgency: "MEDIUM", risk_score: .46, confidence: .89, forecast_demand: 7200, current_inventory: 6400, days_of_inventory: 13.4, expected_stockout_probability: .38, drivers: ["demand_recovery", "capacity_available"], requires_human_approval: true, approval_status: "approved", expected_cost: 60800, created_at: stamp, explanation: { what: "Order 1,600 cases of Sunflower Oil 1L for Chattogram Port.", how_much: "Quantity is sized to restore target coverage without exceeding capacity guardrails.", when: "The order can be released in the current procurement window.", from_where: "Meghna Group Foods is the local supplier for the port lane.", why: "Demand is recovering while the next inbound shipment carries moderate delay risk.", risk: "Supplier capacity is constrained; defer if the shipment ETA improves.", confidence: "89%; forecast interval is narrow for this stable lane." } },
];
