export type Risk = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type Approval = "pending" | "approved" | "rejected" | "executed";

export type Warehouse = { id: string; name: string; region: string; latitude: number; longitude: number; capacity: number; utilization: number; inventory_value: number; risk_score: number; risk_level: Risk; status: "stable" | "watch" | "critical" };
export type Product = { id: string; sku: string; name: string; category: string; unit: string; shelf_life_days?: number | null; is_perishable: boolean };
export type InventoryRow = { id: string; warehouse_id: string; warehouse_name: string; product_id: string; sku: string; product_name: string; category: string; quantity: number; reserved: number; incoming: number; available_inventory: number; average_daily_demand: number; days_of_inventory: number; safety_stock: number; reorder_point: number; stockout_probability: number; excess_inventory: number; inventory_risk: Risk; unit_value: number; updated_at: string };
export type Forecast = { warehouse_id: string; product_id: string; product_name: string; horizon: "7d" | "14d" | "30d"; predicted_demand: number; lower_bound: number; upper_bound: number; confidence: number; model_name: string; model_version: string; generated_at: string };
export type Sentiment = { region: string; product_category: string; sentiment_score: number; sentiment_change: number; demand_signal: number; confidence: number; sample_count: number; trend: "rising" | "stable" | "falling" };
export type Supplier = { id: string; name: string; region: string; on_time_rate: number; lead_time_days: number; lead_time_variance_days: number; active_products: number; capacity_status: "available" | "constrained" };
export type Recommendation = { id: string; decision_type: "RESTOCK" | "TRANSFER" | "NO_ACTION"; warehouse_id: string; warehouse_name: string; product_id: string; product_name: string; sku: string; recommended_quantity: number; supplier_id?: string | null; supplier_name?: string | null; urgency: Risk; risk_score: number; confidence: number; forecast_demand: number; current_inventory: number; days_of_inventory: number; expected_stockout_probability: number; drivers: string[]; requires_human_approval: boolean; approval_status: Approval; expected_cost: number; created_at: string; explanation: { what: string; how_much: string; when: string; from_where: string; why: string; risk: string; confidence: string } };
export type Shipment = { id: string; supplier_name: string; destination: string; vessel_id: string; eta: string; status: string; delay_days: number; risk_score: number; latitude: number; longitude: number };
